### PR TITLE
OCLOMRS-921:Switched the position of the Submit and Cancel button in …

### PR DESCRIPTION
**Pull request by nk183**
# JIRA TICKET NAME:
[OCLOMRS-921](https://issues.openmrs.org/browse/OCLOMRS-921)

# Summary:
image

### CODE REVIEW

**Review by HerbertYiga — APPROVED** [review]
@nk183 Thanks

**Comment by gracepotma** [comment]
@hadijahkyampeire are you able to merge this? :)

**Comment by hadijahkyampeire** [comment]
@gracepotma yes I can but he should first fix the failing tests.

**Comment by hadijahkyampeire** [comment]
I restarted the build, hopefully it will pass and I merge it.

**Comment by nk183** [comment]
@hadijahkyampeire  Now everything is fine please merge this PR

**Comment by nk183** [comment]
@gracepotma , @hadijahkyampeire 
how can it fail I have just switch the button?
please tell

**Comment by hadijahkyampeire** [comment]
Finally, it passed I will go a head and merge it. @nk183 the next time this happens, go to travis and keep rebuilding, it can be a cache error or when requests are queued

**Pull request merged**
