### PR TITLE
OCLOMRS-45: Fix login page UI

### PR DESCRIPTION
**Pull request by emasys**
# JIRA TICKET NAME:
[Fix login page UI](https://issues.openmrs.org/browse/OCLOMRS-45)

# Summary:
Redesign the login page - focus on the size of the form and the submit button. Also, use a custom stylesheet. This is to prevent the login page's design from changing if anyone alters the general stylesheet.

### CODE REVIEW

**Comment by mwaz** [comment]
LGTM

**Comment by dkayiwa** [comment]
From the JIRA ticket description, i expected only stylesheet changes.

**Comment by dkayiwa** [comment]
You need to explain what kind of redesign. What was wrong with the initial design?

**Comment by emasys** [comment]
The initial design broke - The form became too big and the submit button was out of place. We believe this happened because someone in the team customised the general bootstrap stylesheet we were using. While I was fixing it, I tweaked the design a little bit and the team thought it was ok.

**Comment by dkayiwa** [comment]
@mwaz can you help him again? 😊

**Comment by emasys** [comment]
Ticket description has been updated again. @dkayiwa

**Comment by dkayiwa** [comment]
@emasys are you more scared to type on JIRA than here?

**Comment by emasys** [comment]
I'm not scared to type anywhere

**Comment by dkayiwa** [comment]
Then why do you type more here and less on JIRA?

**Comment by emasys** [comment]
No particular reason. However, I think I understand your point, Henceforth I'll endeavour flesh out my stories better on JIRA board.

**Comment by dkayiwa** [comment]
So can you do it?

**Comment by emasys** [comment]
Yes, I can.

**Comment by dkayiwa** [comment]
Can you look into these merge conflicts?

**Comment by emasys** [comment]
@dkayiwa The merge conflicts have been resolved

**Pull request merged**
