### PR TITLE
OCLOMRS-737:Changed text from Add set... to Add set member

### PR DESCRIPTION
**Pull request by HerbertYiga**
Changed text from Add set... to Add set member

Ticket: https://issues.openmrs.org/browse/OCLOMRS-737

### CODE REVIEW

**Comment by HerbertYiga** [comment]
hi @djazayeri  @dkayiwa  @jecihjoy  @Karuhanga  ,this pr explains more of the  blocker that i was explaining during yesterday's ocl call under the CI logs

**Comment by HerbertYiga** [comment]
hi  @dkayiwa could you be having any suggestion on this ??

**Comment by HerbertYiga** [comment]
hi  @dkayiwa   could upgrading the node.js have caused this is error of travis??

**Comment by dkayiwa** [comment]
Can you remove the second commit from this pull request?

**Comment by HerbertYiga** [comment]
@dkayiwa  Hi daniel,i removed the second commit from this pr.

**Comment by HerbertYiga** [comment]
@dkayiwa  i have also attached the screen shots  as requested here https://issues.openmrs.org/browse/OCLOMRS-737

**Pull request merged**
