### PR TITLE
OCLOMRS-949: Use concept url instead of version_url.

### PR DESCRIPTION
**Pull request by hadijahkyampeire**
# JIRA TICKET NAME:
[Concept links should not require a specific version](https://issues.openmrs.org/browse/OCLOMRS-949)

# Summary:
- Used concept URL instead of version_url

### CODE REVIEW

**Comment by HerbertYiga** [comment]
@hadijahkyampeire  i find a some test is breaking ie apps/concepts/pages/tests/e2e/CreateOrEditConceptPage.test.ts

**Comment by ibacher** [comment]
@hadijahkyampeire This seems a little bit different from what I was asking for in the ticket. We don't explicitly need to change any links. I just think we should render something for URLs like: https://openmrs.openconceptlab.org/orgs/CIEL/sources/CIEL/concepts/206/. Hopefully that just means adjusting a route somewhere.

**Comment by hadijahkyampeire** [comment]
Oh I get it I will made the adjustments when we are ready to push this. Thanks @ibacher

**Comment by hadijahkyampeire** [comment]
@ibacher I added another Route that can allow `conceptId` without version, I don't know if that solves the ticket, please review my PR.

**Review by ibacher — APPROVED** [review]
LGTM! Thanks @hadijahkyampeire!

**Pull request merged**
