### PR TITLE
OCLOMRS-989:Create a feature file ready for automated test

### PR DESCRIPTION
**Pull request by jwnasambu**
# JIRA TICKET NAME:
[Create a feature file ready for automated test](https://issues.openmrs.org/browse/OCLOMRS-989)

# Summary:
I created feature files ready for automated testing.

### CODE REVIEW

**Comment by hadijahkyampeire** [comment]
@jwnasambu, thanks for breaking the ground ❤️ ,  I think you should modify this structure to align with the other automated tests for login that we already have i.e instead of first adding folders and the files, just add files to be consistent with what we already have.

Also if it's not too much work, add some scenarios to one or two of the feature files rather than leaving all of them empty, we can modify them if we need to in the near future.

**Comment by hadijahkyampeire** [comment]
Refer to this PR for the structuring https://github.com/openmrs/openmrs-ocl-client/pull/705

**Comment by jwnasambu** [comment]
@hadijahkyampeire thanks for the review and I really get what you are pointing out though I was just following what the ticket requires which I may be wrong on the way I understood it.

**Comment by jwnasambu** [comment]
> Also if it's not too much work, add some scenarios to one or two of the feature files rather than leaving all of them empty, we can modify them if we need to in the near future.

This has its in depended ticket(s) though am already working on one of the tickets though I haven't claimed the ticket.

**Pull request closed without merging**
