### PR TITLE
OCLOMRS-932: Hide retired concepts & add option to include retired concepts

### PR DESCRIPTION
**Pull request by jwnasambu**
# JIRA TICKET NAME:
[General Filter: Hide Retired Concepts & Add Filter option to Include Retired Concepts](https://issues.openmrs.org/browse/OCLOMRS-932)

# Summary:
I changed includeRetired: includeRetired ? 1 : 0
Back to :

includeRetired

to enable filtering of retired concepts well.

### CODE REVIEW

**Comment by HerbertYiga** [comment]
> General Filter: Hide Retired Concepts & Add Filter option to Include Retired Concepts

not sure why this link keeps breaking at my side

**Comment by jwnasambu** [comment]
@HerbertYiga its failing because of this ERROR: `Service 'solr' failed to build: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.`

**Comment by hadijahkyampeire** [comment]
@ibacher please review this, I think we need to maintain the 1 and 0, if anything we actually need to change the true and false since APIv2 is using 1 and 0, we need to spec this ticket well because it looks like it has been confusing over time.

**Comment by hadijahkyampeire** [comment]
@jwnasambu please rebase your branch with master to get the test fixes.

**Comment by ibacher** [comment]
@hadijahkyampeire I'm going from the OCL interface v2 which seems to use `true`/`false`. Here are requests I see when toggling the `includeRetired` setting in the UI:

https://api.openconceptlab.org/concepts/?q=dxtest&page=1&limit=25&includeRetired=false&verbose=false&sortDesc=last_update

https://api.openconceptlab.org/concepts/?q=dxtest&page=1&limit=25&includeRetired=true&verbose=false&sortDesc=last_update

So I think we really do want `true` / `false` there rather than `1` or `0`. See also [the underlying API code that handles this](https://github.com/OpenConceptLab/oclapi2/blob/e56c494af06d0845d1980132751f2b5d28a12811/core/common/views.py#L52).

**Comment by ibacher** [comment]
@jwnasambu Can you rebase this on the lastest `master` which should fix the test failures?

**Comment by jwnasambu** [comment]
@ibacher on my terminal run this commands,
git checkout OCLOMRS-932 
git rebase master
and ended up with this output `Current branch OCLOMRS-932 is up to date.` but the Travis CI is still failing could there be something I am missing out?

**Comment by ibacher** [comment]
Is your local `master` up to date? Try doing:

```
git fetch --all
git rebase upstream master
```

You might have to do a `git push --force` afterwards to update the branch.

**Comment by jwnasambu** [comment]
@ibacher Thanks so much am so glad the build is successful. This is an achievement!

**Comment by hadijahkyampeire** [comment]
@ibacher @jwnasambu I think this ticket has many files which are other people commits, we need to rebase it well to have only commits for this PR.

**Comment by ibacher** [comment]
@hadijahkyampeire That's a good point. Done.

**Pull request merged**
