### PR TITLE
OCLOMRS-1017: Personalise our .yml file and add OCL status badge to the QA dashboard

### PR DESCRIPTION
**Pull request by hadijahkyampeire**
# JIRA TICKET NAME:
[Personalise our .yml file and add OCL status badge to the QA dashboard](https://issues.openmrs.org/browse/OCLOMRS-1017)

# Summary:
- The original workflow would show up as `Build with Node` so I have created a new workflow that is personalized for the dictionary manager.

### CODE REVIEW

**Comment by hadijahkyampeire** [comment]
Screenshot 2021-08-03 at 02 21 22

**Comment by sherrif10** [comment]
Thanks   @hadijahkyampeire  , This configuration only shows the availability of dictionary manager badge  to be among the qa dashboards. if its a workflow based, i think it would have steps that will tell how the workflow should be comprehend. cc @ibacher , i seem not understanding this commit

**Comment by ibacher** [comment]
@sherrif10 So far, we have not really started breaking out tests into different workflow paths the way that has been done for the QA Framework so, for now, it's kind of a big Pass / Fail button. Once we have more tests established we can group them into workflow and come up with separate badges for those if necessary, but for now, we've just got the one big button.

**Review by ibacher — APPROVED** [review]

**Comment by sherrif10** [comment]
Thanks @ibacher  for clarification, and thanks @hadijahkyampeire

**Pull request merged**
