### PR TITLE
OCLOMRS-601: Improved error validation

### PR DESCRIPTION
**Pull request by prathameshm009**
# OCLOMRS-601:  Improve error message validation when a user fails to create a concept.

[Issue: Improve error message validation when a user fails to create a concept.](https://issues.openmrs.org/browse/OCLOMRS-601)

# Summary:
In this commit I've improved error validation, when user fails to create a Concept.

### UI Changes
Now an Toast pops up telling users that they have failed to create a concept

Screenshot from 2020-01-23 02-19-20

### Steps to see new changes
1. Open form to create new Test concept
2. Add some dummy data
3. Refresh the page

Previously, all the data used to get cleared up with no error message, now we have a toast for that

### CODE REVIEW

**Comment by dkayiwa** [comment]
@PrathameshMutkure when one refreshes the browser, i do not expect them to get any error message. All data should just get cleared. The error message should appear only when one attempts to save. Not so?

**Comment by PrathameshMutkure** [comment]
Thanks @dkayiwa for reviewing, The error toast will pop-up if the concept could not be created/saved, that refresh thing is just an example of concept not being able to save (Sorry, I don't know any other way reproduce error).

**Comment by dkayiwa** [comment]
@PrathameshMutkure can you try clicking the save button after disconnecting your network connection to the OCL API Server?

**Comment by PrathameshMutkure** [comment]
> @PrathameshMutkure can you try clicking the save button after disconnecting your network connection to the OCL API Server?

Thanks @dkayiwa, it worked. Its giving the error as expected :)

**Comment by dkayiwa** [comment]
Can you share the screenshot?

**Comment by PrathameshMutkure** [comment]
I was in the proccess of updating the PR but I noticed the error message is different. Here's the screenchot:

Screenshot from 2020-01-30 21-48-39

Sorry for not checking carefully

**Comment by dkayiwa** [comment]
So where does that leave us in regards to this pull request?

**Comment by dkayiwa** [comment]
@PrathameshMutkure any response to the above?

**Comment by PrathameshMutkure** [comment]
> @PrathameshMutkure any response to the above?

I'm really sorry, completely forgot about it due to sessional exams, I'll have a look at code and let you know very soon :)

**Comment by PrathameshMutkure** [comment]
Hii @dkayiwa, looking at the code I can say, we display a success message when the Concept is saved and now I have added an else case to it, so that it displays error message when failed to save concept. Talking about other error messages, I think we have specific error messages for errors, and cases which are not covered (like that refresh thing) will be covered by this else case.

**Comment by dkayiwa** [comment]
@prathameshm009 did you see my comment on the ticket?

**Pull request closed without merging**
