### PR TITLE
OCLOMRS-139: Implement the search through sources while adding bulk c…

### PR DESCRIPTION
**Pull request by abulojoshua1**
# JIRA TICKET NAME:
[Implement the search through sources while adding bulk concepts](https://issues.openmrs.org/browse/OCLOMRS-139)

# Summary:
This is to enable the user to search for a given source and retrieve all the conceptIDs for its concepts.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@abulojoshua1 what is this pr waiting for?

**Comment by abulojoshua1** [comment]
As I explained in the email conversation (Re: Status Update), I had a small issue finding the correct API endpoint to use during my implementation. I already made a communication in the community.

**Comment by dkayiwa** [comment]
Then what is this pull request for?

**Comment by abulojoshua1** [comment]
@dkayiwa, Is it ok if I just close this pull request, for now, I think it will be best if I just take on a new task for now.

**Comment by dkayiwa** [comment]
What are the changes, that you already made, for?

**Comment by abulojoshua1** [comment]
I had implemented the search through concept source in the `add bulk concepts`, once the concepts are fetched from their sources, they can then be added. But the API endpoint I had used just searches for concepts but not from a source for example CEIL.

**Comment by dkayiwa** [comment]
In other words, does this mean that the changes in this pull request are now useless?

**Comment by abulojoshua1** [comment]
No, the changes I made are not useless, they just cannot serve the desired purpose using a wrong API endpoint. Kindly let me know if it is ok with you for me to close this pull request now and re-open it when I get clarity on the right API endpoint to use for this task.

**Comment by dkayiwa** [comment]
yes go ahead

**Pull request closed without merging**
