### PR TITLE
OCLOMRS-485: Mulago (Dictionary) - show the words in parenthesis and CIEL (Source) - show the words in parenthesis	

### PR DESCRIPTION
**Pull request by myrdstom**
# JIRA TICKET NAME:
[Mulago (Dictionary) - show the words in parenthesis and CIEL (Source) - show the words in parenthesis](https://issues.openmrs.org/browse/OCLOMRS-485)

# Summary:

- On the Create a question concept page, Under Answers section, the concept and the dictionary are not clearly differentiated.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Did you take a look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by myrdstom** [comment]
> Did you take a look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

I looked through the link, made some changes and I have discussed this particular PR with @brucemakallan. I think everything is ok with this

**Comment by dkayiwa** [comment]
Can you ask each and every one on your team to look at that page in regards to your pull request and comment here?

**Comment by myrdstom** [comment]
I have rebased and edited the description of this PR. Please confirm that the necessary changes have been made.

**Comment by myrdstom** [comment]
I have adjusted my commit message as per standard. Please confirm that the necessary changes have been made.

**Pull request merged**
