### PR TITLE
OCLOMRS-240:Use SASS for styling

### PR DESCRIPTION
**Pull request by muhozi**
# JIRA TICKET NAME:
[Use SASS for styling](https://issues.openmrs.org/browse/OCLOMRS-240)

# Summary:
To have consistency in styling it is better to have a uniform styling across the application. We have to migrate from using conventional CSS to using SASS for styling so that we'll be able to customize bootstrap SASS variables. In addition we'll benefit from SASS advantages to increase productivity when we building our UI.

### CODE REVIEW

**Comment by muhozi** [comment]
@dkayiwa I was waiting for each teammate's approval before requesting you to merge this branch.

**Comment by dkayiwa** [comment]
@muhozi why have they taken 2 days without reviewing?

**Comment by muhozi** [comment]
@dkayiwa Yesterday I took the time to explain what I have done to my team during team sync because in this task I attached many files and they were wondering if it will not break things. I'm trying to reach out to everyone who hasn't reviewed it.

**Comment by dkayiwa** [comment]
@muhozi if you do not get a response from them by end of the day, ping me.

**Comment by muhozi** [comment]
@dkayiwa I'll do that, thanks.

**Pull request merged**
