### PR TITLE
Add a script to run Cypress in a Docker container

### PR DESCRIPTION
**Pull request by ibacher**
# Summary:

Adds a script to run Cypress tests in a Docker container. This is intended to be used in conjunction with the `start_local_instance.sh` script, so to use it, run:

```sh
./start_local_instance.sh
./run_e2e.sh
./stop_local_instance.sh
```

### CODE REVIEW

**Comment by ibacher** [comment]
@hadijahkyampeire As mentioned on Slack, this should enable you to run our Cypress tests in a Docker container.

**Comment by hadijahkyampeire** [comment]
> @hadijahkyampeire As mentioned on Slack, this should enable you to run our Cypress tests in a Docker container.

Wow! Thanks Ian I am gonna check it out

**Review by hadijahkyampeire — APPROVED** [review]
Thank you so much @ibacher now I can run tests successfully. One request would be to add this step to the ReadMe so that people can know how to run automated tests with docker.

**Comment by hadijahkyampeire** [comment]
🥇 
Screenshot 2021-07-05 at 00 46 45

**Pull request merged**
