### PR TITLE
Vinisha, Bindu | OCLOMRS-831,853,851 | MOBN-1369,1382,1376 | View all public sources, sources under User Organisations and basic details of a source

### PR DESCRIPTION
**Pull request by vinishad**
* Vinisha, Vineela | OCLOMRS-831 | MOBN-1369 | View all sources under User Organisations

* Vineela | OCLOMRS-831 | MOBN-1369 | Add testcases for sources reducer

* Rakesh, Vineela |  OCLOMRS-831 | MOBN-1369 | Refactor test folder structure

* Rakesh, Vineela | OCLOMRS-831 | MOBN-1369 | Add test cases for Personal Sources and Organisational Sources

* Rakesh, Vineela |  OCLOMRS-831 | MOBN-1369 | Modify data test ids and corresponding test cases

* Rakesh, Vineela |  OCLOMRS-831 | MOBN-1369 | Add test cases for ViewSourcesPage and add generic test-utils

Vinisha, Rakesh, Bindu | MOBN-1382 | View the basic details of a source on the Source Dashboard (#7)

* Bindu,Rakesh | OCLOMRS-853 | MOBN-1382 | Add Routes

* Bindu,Rakesh | OCLOMRS-853 |  MOBN-1382 | Add ViewSourcePage and relevant actions, reducers, selectors and types

* Bindu,Rakesh | OCLOMRS-853 | MOBN-1382 | Add SourceForm Component

* Bindu, Rakesh, vinisha | OCLOMRS-853 | MOBN-1382 | Add fields to source details form

* Vinisha, Bindu | OCLOMRS-853 | MOBN-1382 | Remove the edit link on source details page

* Vinisha, Bindu | OCLOMRS-853 | MOBN-1382 | Add tests for reducer and ViewSourcePage

* Vinisha, Bindu | OCLOMRS-853 | MOBN-1382 | Add tests for Source Form and unused imports

* Vinisha, Bindu | OCLOMRS-853 | MOBN-1382 | Feedback comments

* Vinisha, Rakesh | OCLOMRS-853 | MOBN-1382 | Fixed PR review comments

* Vinisha, Rakesh | OCLOMRS-853 | MOBN-1382 | Refactor test folder structure

Co-authored-by: Rakesh Kumar <rakesh.kumar@thoughtworks.com>

Mobn 1376 | View all public sources (#9)

* Vinisha, Rakesh | OCLOMRS-851 | MOBN-1376 | View all public sources

* Vinisha, Rakesh | OCLOMRS-851 | MOBN-1376 | Adds tests and refactoring

* Vinisha, Rakesh | OCLOMRS-851 | MOBN-1376 | Add logic for previous path in ribbon and fix last line visibility in container cards

Co-authored-by: Rakesh Kumar <rakesh.kumar@thoughtworks.com>

Vinisha, Rakesh | OCLOMRS-851 |  MOBN-1376 | Adds test case for utils, fixed card shrink issue (#13)

Co-authored-by: Rakesh Kumar <rakesh.kumar@thoughtworks.com>

Vinisha | OCLOMRS-851 | MOBN-1376 | Modify api from private to public (#16)

# JIRA TICKET NAME:
[OCLOMRS-831](https://issues.openmrs.org/browse/OCLOMRS-831)
[OCLOMRS-853](https://issues.openmrs.org/browse/OCLOMRS-853)
[OCLOMRS-851](https://issues.openmrs.org/browse/OCLOMRS-851)

# Summary:
As a user I want to see the list of my organisations' sources, public sources and basic details of the each source on click of view button

### CODE REVIEW

**Comment by dkayiwa** [comment]
@vinishad is this a pull request for three tickets?

Did you also get a chance to look at the JIRA workflow here? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by kirity-mahanty** [comment]
> @vinishad is this a pull request for three tickets?
> 
> Did you also get a chance to look at the JIRA workflow here? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

Yes Daniel. But in this case all the three cards are related to the different types of sources (public and org). That is why we raised it together. Next time onwards, we will keep 1 PR for each card.

**Comment by dkayiwa** [comment]
@kirity-mahanty and the JIRA Workflow?

**Comment by kirity-mahanty** [comment]
> and the JIRA Workflow?

@dkayiwa Just updated the JIRA workflow with `Request for Code Review`. I could not assign code reviewer name. I added the PR link in the description as well. Please have a look. Thanks!

**Pull request merged**
