### PR TITLE
OCLOMRS-551: When creating a custom concept, the first letter of the class name should be capitalized 

### PR DESCRIPTION
**Pull request by alexkayabula**
# JIRA TICKET NAME:
[When creating a custom concept, the first letter of the class name should be capitalized ](https://issues.openmrs.org/browse/OCLOMRS-551)

# Summary:
When creating custom concepts ensure that all concept class names begin with a capital letter. For example, when one creates a diagnosis concept, the concept class is saved as ***question*** but it should be ***Question***, same for diagnosis and Drug concepts etc.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Is the ticket about the path or the content that you type in?

**Comment by alexkayabula** [comment]
> Is the ticket about the path or the content that you type in?

No, the ticket is not about the path, since the "concept-class" is derived from the "conceptType" in the path, I had to change the casing of the conceptType in each and every path to allow all created concepts to have classes with the right casing.

**Comment by dkayiwa** [comment]
I still do not understand how this prevented one from creating data with any casing that they wanted.

**Comment by alexkayabula** [comment]
> I still do not understand how this prevented one from creating data with any casing that they wanted.

The casing of the "concept-class" is derived from the conceptType. For example, if one created a diagnosis concept, there is no way one could specify the casing of the class field of the concept since it was predefined from the conceptType in the path.

**Before**
Screen Shot 2019-05-03 at 08 51 57
Screen Shot 2019-05-03 at 08 59 29

**After**
Screen Shot 2019-05-03 at 08 53 18
Screen Shot 2019-05-03 at 09 02 09

**Comment by dkayiwa** [comment]
You videos are confusing.
One types malaria while another types HIV

**Comment by alexkayabula** [comment]
> You videos are confusing.
> One types malaria while another types HIV

I have updated the videos and made them more consistent.

**Pull request merged**
