### PR TITLE
OCLOMRS-281: Enforce best style guide by updating linting tools

### PR DESCRIPTION
**Pull request by Duncanian**
# JIRA TICKET NAME:
[Enforce best style guide by updating linting tools](https://issues.openmrs.org/browse/OCLOMRS-281)

# Summary:
Update the project linting tools(ESLint and related packages) and fix linting errors/warnings in the project. To avoid committing work with linting issues add command in Travis config file to check for linting issues so that whenever a work with linting issues is committed Travis check will not pass.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@Duncanian why is this still open?

**Comment by Duncanian** [comment]
@muhozi , I decided to use the Airbnb's default `maximum length of the line` which is 100 chars per line.

**Comment by Duncanian** [comment]
@dkayiwa , am just making the requested changes and after the changes are approved, I will reach out for it to be merged.

**Comment by Michyjones** [comment]
@Duncanian Resolve the conflicts

**Comment by Duncanian** [comment]
@Michyjones , I have resolved them

**Comment by muhozi** [comment]
> @muhozi , I decided to use the Airbnb's default `maximum length of the line` which is 100 chars per line.
Hey @Duncanian, apparently ESLINT is not checking for the maximum length of the line.

For example I checked this line: `const string = 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magnaLorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna';`

**Comment by muhozi** [comment]
@Duncanian also look into the warnings that appear when running the tests, there are introduced changes that are causing this.

**Comment by Duncanian** [comment]
@muhozi , am working on it!

**Pull request merged**
