### PR TITLE
OCLOMRS-890:added clear error message for :release ID already exists

### PR DESCRIPTION
**Pull request by nk183**
# JIRA TICKET NAME:
[OCLOMRS-890:](https://issues.openmrs.org/browse/OCLOMRS-890)

# Summary:
image
image

### CODE REVIEW

**Comment by nk183** [comment]
please help 
it working fine on my pc and don't know why it is failing checks

**Comment by HerbertYiga** [comment]
@k-joseph  @dkayiwa  do you have any thoughts on the cypress  error for this!!

**Review by ibacher — CHANGES_REQUESTED** [review]
@nk183 Thanks for this and for your work digging out the cause! That said, I think we should take a slightly different approach which is to modify the `errorMsgResponse()` function so that:

1. If there's a "detail" element in the response data, we just return the detail
2. If there's not a "detail" element in the response data, we return the response the way we do today

**Comment by nk183** [comment]
>     2. If there's not a "detail" element in the response data, we return the response the way we do today

I am not able to understand by `the response the way we do today`

**Comment by ibacher** [comment]
@nk183 So, I'm suggesting modifying the [`errorMessageResponse()`](https://github.com/openmrs/openmrs-ocl-client/blob/a0df00455fbae8484244366e4420389599a80f80/src/redux/utils.ts#L103) function to some thing like:

```ts
export function errorMsgResponse(response: any) {
  let errorMsgResponse = [];
  const genericErrorMessage =
      "Action could not be completed. Please retry.";

  if (response.data && response.data.has('details') {
    errorMsgResponse.push(response.data.details);
  } else {
    for (let key in response.data) {
      errorMsgResponse.push(
        Array.isArray(response.data[key])
            ? response.data[key].join(',')
            : response.data[key]
      )
    };
  }
  return errorMsgResponse.length > 0 ? errorMsgResponse.join('\n') : genericErrorMessage;
};
```

**Comment by nk183** [comment]
`for (let key in response.data) {
      errorMsgResponse.push(
        Array.isArray(response.data[key])
            ? response.data[key].join(',')
            : response.data[key]
      )
 };`
@ibacher why we are combining all "key value"?

**Comment by nk183** [comment]
@ibacher Can we just do this::
`export function errorMsgResponse(response: any) {
  let errorMsgResponse = [];
  const genericErrorMessage =
      {detail:"Action could not be completed. Please retry."};
  if(response.data){
    return response.data;
  }
  return genericErrorMessage;
};
`

**Comment by hadijahkyampeire** [comment]
@nk183 I think we should go with @ibacher 's function, that way we are sure we won't break anything because I am sure by the time they made that helper, they were considering various formats of errors and wanting to return them in the best way that is easy to work with, in our components.
So let's just add in the case for `details` since it's what we need now.

**Pull request closed without merging**
