### PR TITLE
OCLOMRS-98: Add Functionality To The Search

### PR DESCRIPTION
**Pull request by EleisonC**
# JIRA TICKET NAME:
[OCLOMRS-98: Add Functionality To The Search](https://issues.openmrs.org/browse/OCLOMRS-98)

# Summary:
In this ticket, the following is required;
- Working functionality for the Search for the navigation bar. This will search for all dictionaries at the moment and in later versions, it will be able to search through sources and concepts.
- A new component to render the search results retrieved from the search.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Some merge conflicts here.

**Comment by dkayiwa** [comment]
@emasys looks good to you with the merge conflicts?

**Comment by EleisonC** [comment]
@dkayiwa I have taken care of the merge conflicts

**Comment by emasys** [comment]
lol, You had already commented on that @dkayiwa

**Comment by dkayiwa** [comment]
@emasys looked as if you just commented without reviewing.

**Comment by emasys** [comment]
ok, but I did review it.

**Pull request merged**
