### PR TITLE
OCLOMRS-257: Fix the app CSS files to cater for all the media

### PR DESCRIPTION
**Pull request by Tittoh**
# JIRA TICKET NAME:
[Fix the app CSS files to cater for all the media](https://issues.openmrs.org/browse/OCLOMRS-257)

# Summary:
Previously, some parts of app were not responsive, some were not aligned properly or some elements overflowed out of their containers on smaller devices.
This is fixed by this PR.

### CODE REVIEW

**Comment by AGMETEOR** [comment]
@Tittoh I think that's not the JIRA TICKET NAME. We usually just use the title without having "OCLOMRS-*"

**Comment by Tittoh** [comment]
@muhozi Fixed it

**Comment by dkayiwa** [comment]
@Tittoh did you see these merge conflicts?

**Comment by Tittoh** [comment]
these conflicts came up after another branch was merged.

**Pull request merged**
