### PR TITLE
OCLOMRS-832,  OCLOMRS-833

### PR DESCRIPTION
**Pull request by rakesh-1010**
# JIRA TICKET NAME:
[OCLOMRS-832](https://issues.openmrs.org/browse/OCLOMRS-832)
[OCLOMRS-833](https://issues.openmrs.org/browse/OCLOMRS-833)
# Summary:
[TW] As a user, I want to differentiate the released version of a collection from the unreleased ones so that the user is clear about the active collection in the subscription

[TW] As a user, I want to differentiate the released version of a collection from the unreleased ones so that the user is clear about the active collection in the subscription

### CODE REVIEW

**Comment by dkayiwa** [comment]
@rakesh-1010 one of our conventions is to include the ticket id in the commit message as advised here: https://wiki.openmrs.org/display/docs/Pull+Request+Tips

Do you think you can do that?

**Comment by dkayiwa** [comment]
For the same link above, it would also be great to attach, on the JIRA ticket, a screenshot with the effects of your changes.

**Comment by rakesh-1010** [comment]
> @rakesh-1010 one of our conventions is to include the ticket id in the commit message as advised here: https://wiki.openmrs.org/display/docs/Pull+Request+Tips
> 
> Do you think you can do that?

@dkayiwa reworded the commit message to include jira card number

**Comment by dkayiwa** [comment]
@rakesh-1010 can you also attach, on the JIRA ticket, as screenshot with the user interface effects of your changes, as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dkayiwa** [comment]
@rakesh-1010 did you also take a look at the travis build failure?

**Comment by kirity-mahanty** [comment]
> @rakesh-1010 did you also take a look at the travis build failure?

@dkayiwa There was some issue with the existing test cases regarding timeout. I added wait for that test. It is passing now.

**Comment by dkayiwa** [comment]
Can you also attach, on the JIRA ticket, a screenshot with the user interface effects of the changes, as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by kirity-mahanty** [comment]
> Can you also attach, on the JIRA ticket, a screenshot with the user interface effects of the changes, as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

I attached the screenshots in the JIRA tickets.

**Pull request merged**
