### PR TITLE
OCLOMRS-552: Enable OpenMRS validation for all dictionaries created to prevent duplication

### PR DESCRIPTION
**Pull request by alexkayabula**
# JIRA TICKET NAME:
[Enable OpenMRS validation for all dictionaries created to prevent duplication](https://issues.openmrs.org/browse/OCLOMRS-552)

# Summary:
Enable OpenMRS validation on the dictionaries we create through this application. This will prevent the dictionary from having two concepts with identical preferred names, which is illegal in OpenMRS.

### CODE REVIEW

**Comment by Karuhanga** [comment]
Could you please look into if this behavior is consistent for when someone tries to update a concept with an already existing name?

**Comment by alexkayabula** [comment]
> Could you please look into if this behavior is consistent for when someone tries to **update** a concept with an already existing name?

I have checked it out. There is actually an error. Let me fix it.

**Comment by alexkayabula** [comment]
> > Could you please look into if this behavior is consistent for when someone tries to **update** a concept with an already existing name?
> 
> I have checked it out. There is actually an error. Let me fix it.

The issue is fixed

**Comment by alexkayabula** [comment]
> Could you please look into if this behavior is consistent for when someone tries to **update** a concept with an already existing name?



> Could you please look into if this behavior is consistent for when someone tries to **update** a concept with an already existing name?

This issue is fixed

**Pull request merged**
