### PR TITLE
OCLOMRS-830 View all sources under user profile

### PR DESCRIPTION
**Pull request by venkatavineela**
# JIRA TICKET NAME:
[OCLOMRS-830
](https://issues.openmrs.org/browse/OCLOMRS-830)
# Summary:
[TW] As an organization member, I want to see the list of all the sources that are available under my user profile so that I can get the visibility and access the required source directly

### CODE REVIEW

**Comment by tendomart** [comment]
@venkatavineela  Do you think squashing them is necessary ?

**Comment by dkayiwa** [comment]
@tendomart did you get a chance to look at this? https://talk.openmrs.org/t/rfc-favour-not-squashing-commits-over-squashing-commits/28482

**Comment by tendomart** [comment]
@dkayiwa  , nop. Just seen it now , thanks alot.

**Comment by dkayiwa** [comment]
@venkatavineela  one of our conventions is to include the ticket id in the commit message as advised here: https://wiki.openmrs.org/display/docs/Pull+Request+Tips

Do you think you can do that?

**Comment by dkayiwa** [comment]
From the same pull request tips link above, it would also be great to attach, on the JIRA ticket, a screenshot with the effects of your changes.

**Comment by venkatavineela** [comment]
> @venkatavineela Do you think squashing them is necessary ?

@tendomart I have squashed all the commits into one.

**Comment by venkatavineela** [comment]
> @venkatavineela one of our conventions is to include the ticket id in the commit message as advised here: https://wiki.openmrs.org/display/docs/Pull+Request+Tips
> 
> Do you think you can do that?

Yes @dkayiwa We could do that. Updated the commit messages accordingly.

**Comment by kirity-mahanty** [comment]
> From the same pull request tips link above, it would also be great to attach, on the JIRA ticket, a screenshot with the effects of your changes.

@dkayiwa I attached the screenshots in the JIRA ticket.

**Comment by dkayiwa** [comment]
Did you also get a chance to look at the travis build failure?

**Comment by kirity-mahanty** [comment]
> Did you also get a chance to look at the travis build failure?

It was running fine earlier for both the PRs. But after changing commit message, it is failing due to some timeout issue. We haven't modified any test case. And all the e2e tests are running fine locally.

**Comment by dkayiwa** [comment]
Do you mind pointing me to the timeout error in this build log? https://travis-ci.org/github/openmrs/openmrs-ocl-client/builds/711372899

**Comment by kirity-mahanty** [comment]
> Do you mind pointing me to the timeout error in this build log? https://travis-ci.org/github/openmrs/openmrs-ocl-client/builds/711372899

In the build log, below e2e test is failing:
```
Import existing concept from Source
      1) Should import existing concepts
```
Here is the screenshot attached.
Screenshot 2020-07-26 at 1 39 19 PM

I modified the same for the other [PR](https://github.com/openmrs/openmrs-ocl-client/pull/593).

**Comment by dkayiwa** [comment]
I have rerun this build several times and it consistently fails several times. Could it be a poorly written test?

**Comment by rakesh-1010** [comment]
@dkayiwa travis build has now passed

**Comment by dkayiwa** [comment]
@rakesh-1010 what did you do to make pass?

**Comment by kirity-mahanty** [comment]
> @rakesh-1010 what did you do to make pass?

Both the PRs were failing because of the same test case. After your first PR merge Rakesh rebased the other PR with master.

**Comment by dkayiwa** [comment]
Oh i see!

**Pull request merged**
