### PR TITLE
OCLOMRS-1005: View organisations test

### PR DESCRIPTION
**Pull request by hadijahkyampeire**
# JIRA TICKET NAME:
[View Organisations page/component unit tests](https://issues.openmrs.org/browse/OCLOMRS-1005)

# Summary:
- Add some unit tests for the view organizations page.

### CODE REVIEW

**Review by suruchee — COMMENTED** [review]
Thank you @hadijahkyampeire for initiating the unit test for the organization. But the unit test does not show up while running the npm test, I think it's because of folder name **__tests__** instead of **__test__** as > react-scripts  scans testPathPattern='.*/tests/unit/|.*/__test__/'
I tried with the __test__ and it's running perfectly fine.

**Comment by hadijahkyampeire** [comment]
You are very right @suruchee thanks for catching that I have pushed the fix, when you pull the latest work, I think you will see the test.

**Review by suruchee — APPROVED** [review]
It's working fine.

**Comment by hadijahkyampeire** [comment]
@ibacher please review my PR about unit tests for view organisations.

**Review by ibacher — APPROVED** [review]
Thanks @hadijahkyampeire! LGTM!

**Pull request merged**
