### PR TITLE
OCLOMRS-226: Remove concepts and sources on the UI and the code

### PR DESCRIPTION
**Pull request by kmunene**
# JIRA TICKET NAME:
[Remove concepts and sources on the UI and the code](https://issues.openmrs.org/browse/OCLOMRS-226)

# Summary:
After a discussion during the sprint planning, It was decided that the concepts and sources pages are no longer needed on the application, therefore, they should be removed together with the code behind the features. This was because both features were not part of the MVP.

### CODE REVIEW

**Comment by emmabaye** [comment]
You need to resolve merge conflicts.

**Comment by dkayiwa** [comment]
@kmunene did you just ignore the question above?

**Comment by kmunene** [comment]
@emmabaye I have fixed the merge conflicts.

**Comment by kmunene** [comment]
@dkayiwa No, I wasn't. I am sorry if that is what it looks like. I usually check the reviewer's section to see if there are any existing comments. I hadn't seen your comment, a failure on my part, I apologize. the reason it took a week without getting it merged is since the PR involved deleting code, I wanted the team to test whether any code was breaking.

**Comment by kmunene** [comment]
@dkayiwa I usually don't get notifications on my email because I have them switched off. I have however now have them turned on.

**Pull request merged**
